#!/bin/python3
import math
import os
import random
import re
import sys



if __name__ == '__main__':

    A = []

    for _ in range(6):
        A.append(list(map(int, input().rstrip().split())))
    
    alist = []
    for i in range(4):
        for j in range(4):
            a=sum(A[i][j:j+3])
            # Top Row
            b=A[i+1][j+1]
            # Middle Row
            c=sum(A[i+2][j:j+3])
            # Bottom Row
            alist.append(a+b+c)
    print(max(alist))
